language: node_js
node_js: stable
script:
  - npm install
  - hexo cl
  - hexo g  #生成
after_success:
  - cd ./public
  - git init
  - git config user.name "round-p"  #修改name
  - git config user.email "round2p@gmail.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master  #GH_TOKEN是在Travis中配置token的名称
env:
 global:
   - GH_REF: github.com/round-p/round-p.github.io.git  #设置GH_REF，注意更改yourname

 # - git config --global user.name "happyabbi" 
 # - git config --global user.email "happyabbi@gmail.com"
 # - sed -i'' "/^ *repo/s~github\.com~${blog_use}@github.com~" _config.yml
 # - hexo deploy